### PR TITLE
Update Runtime to 23.08

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by subpop** [comment]
bot, build

**Comment by subpop** [comment]
The test that's failing.
```
flatpak run org.flathub.flatpak-external-data-checker com.github.libresprite.LibreSprite.yaml
 in dir /srv/buildbot/worker/build-x86_64/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run org.flathub.flatpak-external-data-checker com.github.libresprite.LibreSprite.yaml'
 using PTY: False
INFO    src.manifest: Checking 3 external data items
INFO    src.manifest: Started check [1/3] archive gtest/release-1.12.1.tar.gz (from com.github.libresprite.LibreSprite.yaml)
INFO    src.manifest: Skipped check [2/3] archive tinyxml/tinyxml-2.6.2_2.tar.gz (from com.github.libresprite.LibreSprite.yaml)
INFO    src.manifest: Started check [3/3] git libresprite/LibreSprite (from com.github.libresprite.LibreSprite.yaml)
INFO    src.manifest: Finished check [2/3] git libresprite/LibreSprite (from com.github.libresprite.LibreSprite.yaml)
ERROR   src.manifest: Failed to check archive gtest/release-1.12.1.tar.gz with AnityaChecker: Error downloading upstream source: 404, message='Not Found', url=URL('https://codeload.github.com/google/googletest/tar.gz/refs/tags/release-1.14.0')
WARNING src.main: Check finished with 1 error(s)
program finished with exit code 1
elapsedTime=1.530040
```

**Comment by subpop** [comment]
I think this test is asking to update googletest to the latest available version 1.14.0.

**Comment by Vulcalien** [comment]
I think one solution to this would be to simply remove the check for gtest's version. Or try to use the newest version.

**Comment by Vulcalien** [comment]
Found the problem! The gtest authors changed the tags format from `release-x.y.z` to `vx.y.z`.

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
The new runtime needs a more recent version of LibreSprite:

https://github.com/flathub/com.github.libresprite.LibreSprite/pull/20

**Comment by Alexander-Wilms** [comment]
I've updated LibreSprite to the most recent commit so it compiles with FDO 23.08 and hopefully fix https://github.com/LibreSprite/LibreSprite/issues/333

**Pull request closed without merging**
